# Generated by Django 5.0.3 on 2024-04-27 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('P', 'Şahıs'), ('C', 'Şirket')], max_length=1, verbose_name='Müvekkil Tipi')),
                ('name_company_name', models.CharField(max_length=255, verbose_name='İsim Soyisim/Şirket Adı')),
                ('national_id', models.PositiveIntegerField(verbose_name='Tc Kimlik/Vergi No')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon Numarası')),
                ('alternate_phone', models.CharField(max_length=15, verbose_name='Alternatif Telefon Numarası')),
                ('lead_email', models.EmailField(max_length=254, verbose_name='Eposta')),
                ('iban_number', models.CharField(max_length=50, verbose_name='IBAN No')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme Zamanı')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturulan_muvekkiller', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='son_guncellenen_muvekkiller', to=settings.AUTH_USER_MODEL, verbose_name='Son Güncelleyen')),
            ],
            options={
                'verbose_name': 'Müvekkil',
                'verbose_name_plural': 'Müvekkiller',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=50, verbose_name='Plaka')),
                ('brand', models.CharField(max_length=50, verbose_name='Marka/Model')),
                ('color', models.CharField(max_length=50, verbose_name='Renk')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme Zamanı')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturulan_araclar', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='son_guncellenen_araclar', to=settings.AUTH_USER_MODEL, verbose_name='Son Güncelleyen')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadmanagement.lead', verbose_name='Müvekkil')),
            ],
            options={
                'verbose_name': 'Araç',
                'verbose_name_plural': 'Araçlar',
            },
        ),
    ]
