# Generated by Django 5.0.3 on 2024-04-27 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadmanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Alternatif Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturulan_muvekkiller', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='iban_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='IBAN No'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='son_guncellenen_muvekkiller', to=settings.AUTH_USER_MODEL, verbose_name='Son Güncelleyen'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Eposta'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name_company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='İsim Soyisim/Şirket Adı'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='national_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tc Kimlik/Vergi No'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(blank=True, max_length=50, verbose_name='Marka/Model'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Renk'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturulan_araclar', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='last_updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='son_guncellenen_araclar', to=settings.AUTH_USER_MODEL, verbose_name='Son Güncelleyen'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leadmanagement.lead', verbose_name='Müvekkil'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='number_plate',
            field=models.CharField(blank=True, max_length=50, verbose_name='Plaka'),
        ),
    ]
