# Generated by Django 5.0.3 on 2024-05-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadmanagement', '0003_powerofattorney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo'),
        ),
    ]
