# Generated by Django 5.0.3 on 2024-05-08 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadmanagement', '0004_alter_lead_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerofattorney',
            name='is_active',
        ),
    ]
