# Generated by Django 5.0.3 on 2024-04-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagement', '0002_rename_dosyalar_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='arbitration_application_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tahkim Başvuru Tarihi'),
        ),
        migrations.AddField(
            model_name='case',
            name='be_subject_to_arbitration_application',
            field=models.BooleanField(default=True, verbose_name='Tahkim Başvurusuna Tabi Dosya'),
        ),
        migrations.AddField(
            model_name='case',
            name='be_subject_to_insurance_application',
            field=models.BooleanField(default=True, verbose_name='Sigorta Başvurusuna Tabi Dosya'),
        ),
        migrations.AddField(
            model_name='case',
            name='insurance_application_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sigorta Başvuru Tarihi'),
        ),
    ]
