# Generated by Django 5.0.3 on 2024-05-02 10:24

import filemanagement.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagement', '0003_case_arbitration_application_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='office_id',
            field=filemanagement.models.CustomBuroNoField(blank=True, max_length=7, null=True, unique=True, verbose_name='Büro No'),
        ),
    ]
