# Generated by Django 5.0.3 on 2024-05-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagement', '0004_alter_case_office_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Kapanan Dosya'),
        ),
        migrations.AddField(
            model_name='case',
            name='is_closed_with_pre_payment',
            field=models.BooleanField(default=False, verbose_name='Ön Ödeme ile Kapanan Dosya'),
        ),
        migrations.AddField(
            model_name='case',
            name='is_waiting_payment',
            field=models.BooleanField(default=False, verbose_name='İşlemi Biten Ödeme Bekleyen Dosya'),
        ),
    ]
