# Generated by Django 5.0.3 on 2024-05-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagement', '0005_case_is_closed_case_is_closed_with_pre_payment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casesubject',
            options={'verbose_name': 'Dava Konusu', 'verbose_name_plural': 'Dava Konuları'},
        ),
    ]
