# Generated by Django 5.0.3 on 2024-05-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagement', '0008_case_claimed_lost_amount_case_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='have_pre_payment',
            field=models.BooleanField(default=False, verbose_name='Ön Ödemeli'),
        ),
        migrations.AddField(
            model_name='case',
            name='is_personel_lien',
            field=models.BooleanField(default=False, verbose_name='Şahsa İcra'),
        ),
    ]
