# Generated by Django 5.0.3 on 2024-05-10 07:18

import filemanagement.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagement', '0009_case_have_pre_payment_case_is_personel_lien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='insurance_application_id',
        ),
        migrations.AddField(
            model_name='insuranceapplication',
            name='insurance_application_id',
            field=filemanagement.models.CustomInsuranceApplicationIDField(blank=True, editable=False, max_length=7, null=True, unique=True, verbose_name='Sigorta Başvuru Ofis No'),
        ),
    ]
