# Generated by Django 5.0.3 on 2024-04-27 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filemanagement', '0002_rename_dosyalar_case'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_subject', models.CharField(max_length=100, verbose_name='Ödeme Tipi')),
            ],
            options={
                'verbose_name': 'Ödeme Tipi',
                'verbose_name_plural': 'Ödeme Tipleri',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('I', 'Gelir'), ('O', 'Gider')], max_length=20, verbose_name='Gelir/Gider')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ödeme Miktarı')),
                ('payment_date', models.DateField(verbose_name='Ödeme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme Zamanı')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filemanagement.case', verbose_name='Dosya')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturulan_odemeler', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('last_updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='son_guncellenen_odemeler', to=settings.AUTH_USER_MODEL, verbose_name='Son Güncelleyen')),
                ('payment_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountingmanagement.paymentsubject', verbose_name='Ödeme Tipi')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
            },
        ),
    ]
