# Generated by Django 5.0.3 on 2024-05-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_channel',
            field=models.CharField(blank=True, choices=[('B', 'EFT/Havele'), ('C', 'Nakit'), ('LC', 'Barokart')], max_length=20, null=True, verbose_name='Ödeme Kanalı'),
        ),
    ]
