# Generated by Django 5.0.3 on 2024-05-09 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingmanagement', '0002_payment_payment_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_category', models.CharField(max_length=100, verbose_name='Ödeme Kategorisi')),
            ],
            options={
                'verbose_name': 'Ödeme Kategorisi',
                'verbose_name_plural': 'Ödeme Kategorileri',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountingmanagement.paymentcategory', verbose_name='Ödeme Kategorisi'),
        ),
    ]
