# Generated by Django 5.0.3 on 2024-03-21 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50, verbose_name='Departman Adı')),
            ],
            options={
                'verbose_name': 'Departman',
                'verbose_name_plural': 'Departmanlar',
            },
        ),
        migrations.CreateModel(
            name='ExpertStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='İsim')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyisim')),
                ('email', models.EmailField(max_length=254, verbose_name='Eposta')),
                ('national_identity_number', models.CharField(max_length=11, verbose_name='TC Kimlik No')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefon Numarası')),
                ('hire_date', models.DateField(verbose_name='İşe Alım Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme Zamanı')),
            ],
            options={
                'verbose_name': 'Usta/Servis',
                'verbose_name_plural': 'Usta/Servisler',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=50, verbose_name='Bölge Adı')),
            ],
            options={
                'verbose_name': 'Bölge',
                'verbose_name_plural': 'Bölgeler',
            },
        ),
        migrations.CreateModel(
            name='OfficeStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='İsim')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyisim')),
                ('email', models.EmailField(max_length=254, verbose_name='Eposta')),
                ('national_identity_number', models.CharField(max_length=11, verbose_name='TC Kimlik No')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefon Numarası')),
                ('hire_date', models.DateField(verbose_name='İşe Alım Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme Zamanı')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffmanagement.department', verbose_name='Departman')),
            ],
            options={
                'verbose_name': 'Ofis Personeli',
                'verbose_name_plural': 'Ofis Personelleri',
            },
        ),
        migrations.CreateModel(
            name='FieldStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='İsim')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyisim')),
                ('email', models.EmailField(max_length=254, verbose_name='Eposta')),
                ('national_identity_number', models.CharField(max_length=11, verbose_name='TC Kimlik No')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefon Numarası')),
                ('hire_date', models.DateField(verbose_name='İşe Alım Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme Zamanı')),
                ('expert_staffs', models.ManyToManyField(to='staffmanagement.expertstaff', verbose_name='Usta/Servisler')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffmanagement.region', verbose_name='Bölge')),
            ],
            options={
                'verbose_name': 'Saha Personeli',
                'verbose_name_plural': 'Saha Personelleri',
            },
        ),
        migrations.AddField(
            model_name='expertstaff',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffmanagement.region', verbose_name='Bölge'),
        ),
    ]
