# Generated by Django 5.0.3 on 2024-05-03 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanagement', '0002_expertstaff_created_by_expertstaff_last_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertstaff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Eposta'),
        ),
        migrations.AlterField(
            model_name='expertstaff',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='expertstaff',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='İşe Alım Tarihi'),
        ),
        migrations.AlterField(
            model_name='expertstaff',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Soyisim'),
        ),
        migrations.AlterField(
            model_name='expertstaff',
            name='national_identity_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='TC Kimlik No'),
        ),
        migrations.AlterField(
            model_name='expertstaff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='expertstaff',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staffmanagement.region', verbose_name='Bölge'),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Eposta'),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='expert_staffs',
            field=models.ManyToManyField(blank=True, null=True, to='staffmanagement.expertstaff', verbose_name='Usta/Servisler'),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='İşe Alım Tarihi'),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Soyisim'),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='national_identity_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='TC Kimlik No'),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='fieldstaff',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staffmanagement.region', verbose_name='Bölge'),
        ),
    ]
