# Generated by Django 5.0.3 on 2024-05-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_power_of_attorney_files', models.IntegerField(default=0)),
                ('total_monthly_power_of_attorney_files', models.IntegerField(default=0)),
                ('total_files', models.IntegerField(default=0)),
                ('total_monthly_files', models.IntegerField(default=0)),
                ('total_unclosed_files_without_insurance_application', models.IntegerField(default=0)),
                ('total_insurance_application_pending_files', models.IntegerField(default=0)),
                ('total_insurance_application_files', models.IntegerField(default=0)),
                ('total_delayed_insurance_application_files', models.IntegerField(default=0)),
                ('total_arbitration_application_files', models.IntegerField(default=0)),
                ('total_delayed_arbitration_application_files', models.IntegerField(default=0)),
                ('total_personal_lien_files', models.IntegerField(default=0)),
                ('total_files_without_arbitration_application', models.IntegerField(default=0)),
                ('total_payment_pending_files', models.IntegerField(default=0)),
                ('total_closed_files', models.IntegerField(default=0)),
                ('total_pre_payment_files', models.IntegerField(default=0)),
                ('total_profitable_closed_files', models.IntegerField(default=0)),
                ('total_unprofitable_closed_files', models.IntegerField(default=0)),
            ],
        ),
    ]
